### PR TITLE
Require presence of a begin() member function for map/vector conversions.

### LINKED ISSUE #109: Constructor for vector-like objects matches std::optional<...>
This problem actually surfaced with gcc 6 when trying to create a copy of `std::experimental::optional<json11::Json>`, but I believe these two lines simulate the underlying issue even with earlier gcc versions:

```c++
std::experimental::optional<json11::Json> foo;
json11::Json foo2 = foo;
```

The compilation fails with:

```
error: 'const class std::experimental::fundamentals_v1::optional<json11::Json>' has no member named 'begin'
     Json(const V & v) : Json(array(v.begin(), v.end())) {}
```

I think the correct error would be that there is no matching `operator=`. The `enable_if` condition for vector-like objects is too loose, because optionals also have a member type `value_type`.

A quickfix (checking for presence of a `begin()` function) seems to solve the issue.

### PR DESCRIPTION
**Pull request by j4cbo**
Because this could otherwise false-positive on things like std::optional, which
also has a value_type member type, but is not a container.

Fixes #109.

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@j4cbo, it looks like you've already signed the Dropbox CLA. Thanks!

File: json11.hpp [hunk 1]
```diff
@@ -106,14 +106,14 @@ class Json final {
     Json(const T & t) : Json(t.to_json()) {}
 
     // Implicit constructor: map-like objects (std::map, std::unordered_map, etc)
-    template <class M, typename std::enable_if<
+    template <class M, typename = decltype(std::declval<M>().begin()), typename std::enable_if<
```
Comment (artwyman) [inline json11.hpp]: Is there a way to work this into the enable_if?  Seems like it becomes a bit harder to understand since you're doing two different forms of compatibility checks.  This one is direct SFINAE while enable_if hides it inside of the more boolean syntax.

**Comment by j4cbo** [comment]
Changed to look directly at the return value of begin() instead of depending on typedefs.
